# Generated by Django 4.2.6 on 2024-02-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_liked_by_posts_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='like',
            new_name='liked_by',
        ),
    ]
