# Generated by Django 4.2.6 on 2024-02-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_post',
            field=models.ManyToManyField(related_name='postsave', to='myapp.posts'),
        ),
    ]
